<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_org.openqa.selenium.concurrent</name>
   <tag></tag>
   <elementGuidId>2693ef93-5caf-483a-a16b-858b156a6ffa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'org.openqa.selenium.concurrent')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.subTitle > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d797af9d-38a4-4165-b646-0af04c2ef551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>package-summary.html</value>
      <webElementGuid>18b74a0f-0da7-4062-978a-65e839a272bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>org.openqa.selenium.concurrent</value>
      <webElementGuid>68c677a8-42f9-41f1-a383-00724242a109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;header&quot;]/div[@class=&quot;subTitle&quot;]/a[1]</value>
      <webElementGuid>3ea6b458-fbac-4807-8ccf-728176973c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_GuardedRunnable/iframe_classFrame</value>
      <webElementGuid>47c5d5d1-7104-490a-89aa-6cc840ac6bce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'org.openqa.selenium.concurrent')]</value>
      <webElementGuid>01b47678-ddb4-4033-bc08-7080746d4023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Package'])[2]/following::a[1]</value>
      <webElementGuid>cb3a13fa-5fd1-4fa3-9c96-72c45369167c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Method'])[2]/following::a[2]</value>
      <webElementGuid>17b074a7-ef21-4ddd-816d-f428187c5398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class GuardedRunnable'])[1]/preceding::a[1]</value>
      <webElementGuid>7eeac814-f8fb-453d-ab60-a98608260945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='java.lang.Object'])[1]/preceding::a[1]</value>
      <webElementGuid>1163cd60-c088-414e-a855-d005aeed2ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='org.openqa.selenium.concurrent']/parent::*</value>
      <webElementGuid>f7ad99f1-5fff-4129-9989-8aee93981b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'package-summary.html')])[2]</value>
      <webElementGuid>2134078e-7900-425e-88f6-269df4c30d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/a</value>
      <webElementGuid>fd9c1499-ed71-4243-88c6-194b7a4ce2a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'package-summary.html' and (text() = 'org.openqa.selenium.concurrent' or . = 'org.openqa.selenium.concurrent')]</value>
      <webElementGuid>8432eff0-f2b7-4932-b2e2-e00b8a23dad5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
